#! /usr/bin/env python3
"""
    Static file script
"""

from cloudinary.uploader import upload as c_uploader, destroy as destroyer

# from cloudinary.utils import cloudinary_url


def upload(loc_file, folder, ** kwargs):
    """
        Uploads the given media file to the cloudinary storage
    """
    return c_uploader(loc_file, folder=folder, **kwargs)


def destroy(pub_key):
    """
        Deletes the resource of the given public pub_key
    """

    return destroyer(pub_key).get('result')
