#! /usr/bin/env python3
"""
    Static file script
"""

from cloudinary.uploader import upload as c_uploader
# from cloudinary.utils import cloudinary_url


def upload(loc_file):
    """
        Uploads the given media file to the cloudinary storage
    """
    return c_uploader(loc_file)
